# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
    - init: >
          gp open README.md;
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -;
          poetry install;
      command: >
          gp open README.md;
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
    - port: 9000-9099
      onOpen: ignore

# Install necessary packages
image:
    file: .gitpod.dockerfile

vscode:
    extensions:
        - ms-toolsai.jupyter
        - ms-toolsai.jupyter-keymap
        - ms-toolsai.jupyter-renderers 
        - ms-python.python
        - ms-pyright.pyright
